### ISSUE TITLE
自然言語を入力するUI変更

### ISSUE THREAD

**Issue by kagawa0710** [kagawa0710/3c_typelog#6]

**Comment by kagawa0710** [comment]
行数を表示しない。プログラミング用のハイライトをしない。

**Comment by kagawa0710** [comment]
botテスト

**Comment by kagawa0710** [comment]
@uyukigakata 
ありがとうございます！みてみました。
機能的な面ではハイライトがされないというのは成功していると思います。
箇条書きですが、下に気になった部分をまとめてみました。


途中かもしれませんが、表示を消したらその定義も消すようにしていってもらえるとコードがスッキリすると思います。
例えば、現状でハイライトを使っていないので、Prismをimportをする必要はないと思います。
もし、vscode使ってて、設定してないのであれば下のあたり設定すると便利かもしれません。
https://qiita.com/kimascript/items/e0eeccf262df26990613
<img width="880" alt="Screenshot 2024-08-12 at 12 42 05" src="https://github.com/user-attachments/assets/87e7d8b6-4958-41a5-85b5-74e238eabab8">
自分の手元ではこのようになってます。


一旦pushして欲しいということだったので、今回は問題ないのですが、
高垣さんが理解する用にコメントを追加しているのかなと思っていて、最終的にプルリクを送る場面では多すぎるコメントは消して欲しいです。(可読性と次にコード修正する際に邪魔になるため。)


gitで管理しているので、不要なコードはコメントアウトではなく消してもらえるとわかりやすいです。
↓のようにdiffが見えます。
https://github.com/kagawa0710/3c_typelog/compare/main...feature/6



ちなみにここの①というコメントはなんでしょうか？
https://github.com/kagawa0710/3c_typelog/compare/main...feature/6#diff-ea851579c12a049d14dcb99c3d2eaf0e6336b2cfea3241e281a60df0b89ef607R78

**Comment by kagawa0710** [comment]
@uyukigakata 
変更一通り完了した認識であってますか？

**Comment by uyukigakata** [comment]
@kagawa0710 
行数を表示しない。プログラミング用のハイライトをしない。
変更一通り終わりました。確認お願いします。
連絡遅れてしまってすいません。

**Comment by kagawa0710** [comment]
@uyukigakata 
ありがとうございます！

<img width="238" alt="Screenshot 2024-08-15 at 13 25 33" src="https://github.com/user-attachments/assets/4cd9cf4e-acb9-472d-8631-f5f1cb4b981c">

"/nl"のここの部分、行数を表示するために左側のスペースを確保していると思うので、枠ごとなくてもいいかなと思います。

また、Editorとして使っている"react-simple-code-editor"自体、codeを書くために導入したライブラリなので、自然言語に適したものに変更した方がいいと思います。




単なる興味ではあるのですが、下で聞いている
https://github.com/kagawa0710/3c_typelog/issues/6#issuecomment-2283064684
> ちなみにここの①というコメントはなんでしょうか？
https://github.com/kagawa0710/3c_typelog/compare/main...feature/6#diff-ea851579c12a049d14dcb99c3d2eaf0e6336b2cfea3241e281a60df0b89ef607R78

https://github.com/kagawa0710/3c_typelog/commit/5a370ce614d2fc9e9f399a686e652e094c8e8fd7#diff-ea851579c12a049d14dcb99c3d2eaf0e6336b2cfea3241e281a60df0b89ef607R78
現状だと↑の、これはなんだったのですか？w

**Comment by kagawa0710** [comment]
作業的には、feature/8を修正→プルリクを送る。→feature/6にfeature/8をマージ
この流れで作業すると良いと思います。

**Comment by kagawa0710** [comment]
feature/6ブランチでの作業は進めてもらって問題ないです。

**Comment by uyukigakata** [comment]
@kagawa0710 
修正しました。
・"/nl"のここの部分、行数を表示するために左側のスペース削除
・Editorモジュール削除
・/nlで使用していないコード部分の削除
