### ISSUE TITLE
書いている途中に再生ボタンを押せないように変更

### ISSUE THREAD

**Issue by uyukigakata** [kagawa0710/3c_typelog#8]
・開始ボタンを連続で押すと、残り時間が初期化されて360秒に戻る
　　　　　　　　　　　　　　↓
・3開始ボタンを連続で押した分経過時間が増加する

例）開始ボタン1回
360→359→358→357

例）開始ボタン2回連続で押した場合
360→358→356

**Comment by kagawa0710** [comment]
@uyukigakata 
ありがとうございます！issueの書き方も詳細で素晴らしいです。
どこのページで発生してるかなども書かれていればもっと良いかと思います！

いい勉強になりそうなので、修正を高垣さんに依頼できればと思っています。
わからないことあればサポートしますので聞いてください。

まず、下を考えてもらえれば！
こちら具体的にコード上で何が起きていて、どのように修正したら良いでしょうか？

**Comment by uyukigakata** [comment]
@kagawa0710 
/Codepage/CodePage.jsx
/NIPage/NIPage.jsx　のファイルのデータで、問題があります。

開始ボタンを連続で押すと経過時間が倍減少してしまうので、開始を何回押しても
360→359→358のように1秒ずつカウントしたい

・開始を連続で押したかというと、書くことに対して、最初から書き直したいと考えたこと。
・開始を押してから色々考えて時間が経過してしまったため

解決すること
・開始ボタンを押して360秒の戻って、カウントが1秒ずつ減っていくようにしたい。

提案
・リセットボタンなど（自然言語の場合あってもいいかも）

**Comment by kagawa0710** [comment]
@uyukigakata 
めちゃ詳細で良きです。


> 開始ボタンを連続で押すと経過時間が倍減少してしまうので、開始を何回押しても
360→359→358のように1秒ずつカウントしたい
> 
> ・開始を連続で押したかというと、書くことに対して、最初から書き直したいと考えたこと。
> ・開始を押してから色々考えて時間が経過してしまったため

ここですが、まずリセットをするというのが、自分的にはこのアプリを使って思考が見たいという意図に反しているのかなと思います。
使い方にもよると思うのですが、やり直せるというのは今までの完成した文章を提出してもらうというようなものに近いのかなと思います。
自分の考えでは、リセットボタンには反対で、一度再生ボタンをおして文章を書いている間は再生ボタンを押せなくするなどの対応でいいと思います。
こちら、松田さんの意見も聞きましょう！


ちなみに、リセットボタンを設置した際、再生ボタンは今まで通りなのでしょうか？

**Comment by mayu-matsuda** [comment]
先ほどディスコードにも流したのですが、
パソコンの前で考え込んでしまった時間＝記録としては何も動かない時間　は後から見るときに意外と退屈でした…。
思考の過程が見えることの楽しさは、ぐちゃぐちゃと書き直すところにあるのかもしれません。
土台があって何かを書き直すというシチュエーションであれば、リセットボタンなしの方が際立つと思いますし、アイデア出しであればリセットボタンありの方がよいと思います。

自然言語とプログラミングで分かれているように、アプリ内にルート分岐を作るのも良いかも。

**Comment by uyukigakata** [comment]
確かにリセットボタンがあったら、相手の思考した時間や書いた文章の履歴の削除に繋がるため必要ないのかとも思いました。

リセットボタンを付ける場合、再生ボタンを一度押すとそれ以降終了するまで（時間が終了するまで）押しても何も起きないように出来ればいいと思いました。

現状修正したいこと
例）再生ボタンを押す(1～n回)
360→359→358

例) 2回連続で押した場合でも
現在の経過時間が249秒時の場合
249→248→247（押しても時間がリセットされずそのまま経過する）

自分の考え
・文章を書く際の時間制限をなくす①

・時間ありの場合リセットボタンを追加の場合②
1度ダウンロードしてから再度ダウンロードするまでのデータを履歴として残す

例）文章を作成してダウンロードして、また文章を書く（ここから）
　　　　　　　　　　　　　↓
時間を使って考え込んでしまう（時間がなくなる）
　　　　　　　　　　　　　↓
リセットボタンを押す
　　　　　　　↓
再度書き始める
　　　　　　↓
終了ボタンを押してデータをダウンロード（ここまで）

消したり書いたりといったアナログの良さを可視化できる気がした。

**Comment by kagawa0710** [comment]
@uyukigakata 
一旦バグ修正という意味では、書いている途中には再生ボタンを押せないように変更してもらって良いでしょうか？


(簡単に決まるかと思ってここで始めてしまったのですが)リセットをして良いかというのは、バグ修正を超えた機能をどうするかという部分かなと思うので別issueを立てます。

**Comment by uyukigakata** [comment]
@kagawa0710 
> @uyukigakata 一度バグ修正という意味では、書いている途中には再生ボタンを押せないように変更してもらって良いでしょうか？

・開始ボタンを押してから時間が終了するまで
・終了ボタンを押すまで
開始ボタンを押せないように修正しました。

feature/8というブランチを作成してpushしました。
確認お願いします。

**Comment by kagawa0710** [comment]
@uyukigakata 
useStateで変数を定義して、MUIボタンのpropsのdisableを使っていて変更内容素晴らしいです。
https://github.com/kagawa0710/3c_typelog/compare/main...feature/8#diff-ea851579c12a049d14dcb99c3d2eaf0e6336b2cfea3241e281a60df0b89ef607R144


コードに関しては、一点、runという変数名が分かりずらい気がします。
諸説ありますが、bool値にはisをつけて欲しいので、isRunningに変更してもらえると嬉しいです。


また、gitの扱い方について、こういった作業をするときは常にmainからブランチを切るのが原則かなと思います。
おそらく、feature/6からfeature/8ブランチを切ったと思うのですが、feature/6のコミットが含まれていると思います。
https://github.com/kagawa0710/3c_typelog/compare/main...feature/8
例えはfeature/6はうまくいってないので後でmainにマージしたいけど、feature/8はうまくいっているのでmainにマージしたいというのができなくなってしまうと思います。
(修正大変なので、今回は修正不要です。)


こちら変数名変更後、mainに対しプルリクを送って欲しいです。

**Comment by uyukigakata** [comment]
@kagawa0710 
変数名変更して、プルリクエスト送りました。

> また、gitの扱い方について、こういった作業をするときは常にmainからブランチを切るのが原則かなと思います。 おそらく、feature/6からfeature/8ブランチを切ったと思うのですが、feature/6のコミットが含まれていると思います。
 
mainからきることをしていなかったです。すいません。

**Comment by kagawa0710** [comment]
@uyukigakata 
プルリクではなくマージしてしまってます。
権限としてmainにマージができる状態になってるのもよくなかったですが、わからない場合や自信がない場合は一度聞いてください。。

(誤って欲しいのではなく。。。)内容を理解しましたか？

**Comment by uyukigakata** [comment]
@kagawa0710 
> 作業的には、feature/8を修正→プルリクを送る。→feature/6にfeature/8をマージ この流れで作業すると良いと思います。

issue#6の方でfeature/6にfeature/8のデータをマージすれば良いと思い、
![image](https://github.com/user-attachments/assets/364ec682-5322-4d43-bf1e-e2ae1d9d5e6c)
これが間違っていたらすいません。理解していないので、今日のミーティング時に教えてもらってもいいですか？

**Comment by kagawa0710** [comment]
@uyukigakata 
okです。通話しながらやりましょう。

"feature/6にfeature/8をマージ "こっちはできているのですが、前半の"feature/8を修正→プルリクを送る。"こっちができていないです。
